# ========================================
# Import Python Modules (Standard Library)
# ========================================
import argparse
import os
import sys

# ==================
# Python Path Update 
# ==================
sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'ui'))
sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'pipeline'))

# ========================================
# Import Python Modules (Project-specific) 
# ========================================
from db import DB, DBType
from pysa_taint_parser import Parser as PysaParser
from custom_postprocessing import PostprocessorCls

# =========
# Functions
# =========
def process_program_input():
    parser_obj = argparse.ArgumentParser(description='Launches the custom postprocessing of the \
        SQLite database generated by the SAPP Tool.')
    parser_obj.add_argument('-d', '--database-path', action='store', type=str, metavar='database', \
        help='Database - Full path of SQLite database to be processed', required=True)
    parser_obj.add_argument('-r', '--repository-path', action='store', type=str, metavar='repository', \
        help='Repository - Full path of code repository to be processed', required=True)
    return parser_obj.parse_args()
    
        
# ====
# Main
# ====
if __name__ == '__main__':
    message = '--- SQLite database custom postprocessor ---'
    print(len(message) * '-')
    print(message)
    print(len(message) * '-')
    args = process_program_input()
    print(f'--- Database to be processed: {args.database_path} ---')
    print(f'--- Repository to be processed: {args.repository_path} ---')
    # Initialize database interface object
    database = DB(DBType.SQLITE, args.database_path, assertions=True)
    # Initialize parser class variable
    parser_class = PysaParser
    # Create instance of the PostprocessorCls class
    postprocessor_obj = PostprocessorCls(
        database=database,
        repository_directory=args.repository_path,
        parser_class=parser_class
    )
    # Call relevant methods of the PostprocessorCls class
    postprocessor_obj.setup()
    postprocessor_obj.issue(1)
    # An issue must be selected (with the issue method) prior to calling the trace method 
    postprocessor_obj.trace()
    
    
    
    
    
    

